version: 2.1
parameters:
  commit-message:
    type: string
    default: $(git log --format=oneline -n 1 $CIRCLE_SHA1)
executors:
  docker-node:
    docker: 
      - image: cimg/node:14.10.1
        auth:
          username: danecando
          password: $DOCKERHUB_PASSWORD
jobs:
  build-dev:
    executor: docker-node
    steps:
      - checkout
      - run: echo "<< pipeline.parameters.commit-message >>"
  build-prod:
    executor: docker-node
    steps:
      - checkout
      - run: echo "build-prod job ran"
workflows:
  build-deploy-prod:
    jobs:
      - build-prod
    when:
      and:
        - equal: [<< pipeline.parameters.commit-message >>, /build-prod*/]
build-deploy-dev:
    jobs:
      - build-dev
    when:
      and:
        - equal: [<< pipeline.parameters.commit-message >>, /build-dev*/]
