version: 2.1
parameters:
  commit-message:
    type: string
    default: $(git log --format="%s" -n 1 $CIRCLE_SHA1)
executors:
  docker-node:
    docker: 
      - image: cimg/node:14.10.1
        auth:
          username: danecando
          password: $DOCKERHUB_PASSWORD
jobs:
  build-dev:
    executor: docker-node
    steps:
      - when:
        condition:
          and:
            - equal: [/.*build-dev/, << pipeline.parameters.commit-message >>]
        steps:
          - checkout
          - run: echo "<< pipeline.parameters.commit-message >>"
  build-prod:
    executor: docker-node
    steps:
    - when:
        condition:
          and:
            - equal: [/.*build-prod/, << pipeline.parameters.commit-message >>]
        steps:
          - checkout
          - run: echo "<< pipeline.parameters.commit-message >>"
# workflows:
#   build-deploy-prod:
#     jobs:
#       - build-prod
#     when:
#       and:
#         - equal: [build-prod, << pipeline.parameters.commit-message >>]
#   build-deploy-dev:
#       jobs: 
#         - build-dev
#       when:
#         and:
#           - equal: [/.*build-dev/, << pipeline.parameters.commit-message >>]
